### ISSUE TITLE
Problem with dependency-profiles

### ISSUE THREAD

**Issue by pbauer** [zopefoundation/Products.GenericSetup#19]
There seems to be an issue with https://github.com/zopefoundation/Products.GenericSetup/pull/16

After this was merged and enabled in the Plone 5 coredev the following problem was observed the workflow 'comment_review_workflow' from `plone.app.discussion` is not installed upon creating a new site.

Steps to reproduce:
- create new site
- go to http://localhost:8080/Plone/portal_workflow/manage_main

**Comment by mauritsvanrees** [comment]
This seems a problem specific during the creation of a Plone Site, where lots of profiles get installed. Plone relies on reapplying all profiles. This should be fixed in Plone.  I have committed a temporary fix there that calls runAllImportStepsFromProfile with as dependency strategy the old 'reapply all'.

**Comment by pbauer** [comment]
The pr to include GS master still produces failures: https://github.com/plone/buildout.coredev/pull/114

**Comment by mauritsvanrees** [comment]
All is well here.
