### ISSUE TITLE
1.8.0 creates breakage with plone.app.testing

### ISSUE THREAD

**Issue by do3cc** [zopefoundation/Products.GenericSetup#22]
This is probably not a bug of GS, but tbh I am not sure where this bug belongs, I'll add it to plone.app.testing as well :-)

Some context:
When using the PloneSandbox layer in tests, the layer will create a demostorage and wrap the current storage. it will also "reset" the zcml config, doesn't matter, as the layer will rerun the zcml config anyway.

With 1.8.0 this doesn't happen any more with nested PloneSandboxes.
Nested DemoStorages aren't a problem, zcml reconfigurations are also not a problem, the Layer will rerigster plone ande dependencies, but:
Persistent tools registered via componentregistry.xml are gone.
The tool is still available in the database, but the registration that has happened in the import step is gone.

**Comment by do3cc** [comment]
Small update:
I stil do not grasp the problem properly. I thought this is related to nested Sandbox Layers, but it is not. It happens without nested layers. Weird...

**Comment by do3cc** [comment]
Oh thank god I found it.
I am confident now that it is a bug in GenericSetup.
my Test layer applied a base profile.
This base profile also as a componentregistry.xml.
Base profiles get teld to purge everything.
Even though stuff got purged dependent profiles are not getting reapplied. I think here lies the problem.

**Comment by do3cc** [comment]
@mauritsvanrees Do you have an opinion here on what to do? Maybe it is just a bad idea to reimport the base profile again?
I fixed all my issues by not doing it.

**Comment by mauritsvanrees** [comment]
Reimporting base profiles is indeed bad. Some tests do that (probably inadvertently). I think Products.CMFPlacefulWorkflow did that and I thought I or Philip fixed something there for Plone 5.0. Related fix: https://github.com/plone/Products.CMFPlacefulWorkflow/commit/3c7bd2bf7835b1249ccf8c9cb33e0c6e622480f4

See https://github.com/zopefoundation/Products.GenericSetup/pull/18 for an idea that applying a base profile should probably purge all registered profile versions, because in all likelihood they will need to be applied again, indeed because the base profiles are usually imported in full purge mode.

**Comment by mauritsvanrees** [comment]
I think this is fine with the latest 1.8.1, released last week.
Please reopen if you think this is still a problem.
